#!/usr/bin/env python
# coding: utf-8
"""Generate jiecunit_macros.iec — N-arity helpers for _JIEC_TESTNAMES_LIST_.

Generates:
  _STRINGIFY_N(a1,...,aN)            -> @a1, @a2, ..., @aN   (string-ify N identifiers)
  _JIEC_BIND_N(a1,...,aN)            -> program a1 with JiecUnitTask; ... (N task bindings)
  _JIECUNIT_EXTERN_PROGRAMS_N(...)   -> extern program a1 end; ... end (N extern declarations)

Dispatchers:
  _JIEC_STR_(...)               -> _JIEC_STR_N(N, ...)
  _JIEC_BIND_(...)              -> _JIEC_BIND_N(N, ...)
  _JIECUNIT_EXTERN_PROGRAMS(...)-> _JIECUNIT_EXTERN_PROGRAMS_N(N, ...)

Usage:
  python scripts/generate_macros.py [--max N]  (default: 512)
  python scripts/generate_macros.py --max 1024
Output: src/jiecunit_macros.iec
"""
import argparse
import os

_STRINGIFY_MACRO_NAME = "_STRINGIFY"
_TASK_BIND_MACRO_NAME = "_JIECUNIT_TASK_BIND"
_EXTERN_PROGRAMS_MACRO_NAME = "_JIECUNIT_EXTERN_PROGRAMS"
TASK_NAME = "JiecUnitTask"

_HEADER = f"""\
{{#ifndef __JIECUNIT_MACROS_IEC__}}
{{#define __JIECUNIT_MACROS_IEC__}}

// -----------------------------------------------------------------------
// Auto-generated by scripts/generate_macros.py  DO NOT EDIT BY HAND
//
// {_STRINGIFY_MACRO_NAME}_N(a1,...,aN) -> @a1, @a2, ..., @aN
// {_TASK_BIND_MACRO_NAME}_N(a1,...,aN) -> program a1 with {TASK_NAME}; ...
// {_EXTERN_PROGRAMS_MACRO_NAME}_N(a1,...,aN) -> extern program a1 end; ... end
// -----------------------------------------------------------------------
"""

_FOOTER = """\
{#endif}
"""


def _params(n):
    # type: (int) -> str
    return ', '.join('a{}'.format(i + 1) for i in range(n))


def generate(max_n):
    # type: (int) -> str
    lines = [_HEADER]

    # --- _JIEC_STR_N ---
    lines.append(f"// Stringify N identifiers: {_STRINGIFY_MACRO_NAME}_N(a1,...,aN) -> @a1, @a2, ..., @aN")
    for n in range(1, max_n + 1):
        params = _params(n)
        values = ', '.join('@a{}'.format(i + 1) for i in range(n))
        lines.append('{' + '#define {}_{}({}) {}'.format(_STRINGIFY_MACRO_NAME, n, params, values) + '}')
    lines.append('')

    # --- _JIEC_STR_ dispatcher ---
    lines.append(f"{{#define {_STRINGIFY_MACRO_NAME}_N(n, ...) {_STRINGIFY_MACRO_NAME}_@@n(__VA_ARGS__)}}")
    lines.append(f"{{#define {_STRINGIFY_MACRO_NAME}_(...) {_STRINGIFY_MACRO_NAME}_N(__VA_ARGC__, __VA_ARGS__)}}")
    lines.append('')

    # --- _JIEC_BIND_N ---
    lines.append("// Bind N programs to {}: _JIEC_BIND_N(a1,...,aN) -> program a1 with {}; ...".format(
        TASK_NAME, TASK_NAME))
    for n in range(1, max_n + 1):
        params = _params(n)
        bindings = ' '.join('program a{} with {}: a{}();'.format(i + 1, TASK_NAME, i + 1) for i in range(n))
        lines.append('{' + '#define {}_{}({}) {}'.format(_TASK_BIND_MACRO_NAME, n, params, bindings) + '}')
    lines.append('')

    # --- _JIEC_BIND_ dispatcher ---
    lines.append(f"{{#define {_TASK_BIND_MACRO_NAME}_N(n, ...) {_TASK_BIND_MACRO_NAME}_@@n(__VA_ARGS__)}}")
    lines.append(f"{{#define {_TASK_BIND_MACRO_NAME}_(...) {_TASK_BIND_MACRO_NAME}_N(__VA_ARGC__, __VA_ARGS__)}}")
    lines.append('')

    # --- _JIECUNIT_EXTERN_PROGRAMS_N ---
    lines.append(
        "// Forward-declare N programs as extern stubs: "
        "{}_N(a1,...,aN) -> extern program a1 end; ... end".format(_EXTERN_PROGRAMS_MACRO_NAME))
    for n in range(1, max_n + 1):
        params = _params(n)
        decls = '; '.join('program a{} end'.format(i + 1) for i in range(n))
        lines.append('{' + '#define {}_{}({}) extern {} end'.format(
            _EXTERN_PROGRAMS_MACRO_NAME, n, params, decls) + '}')
    lines.append('')

    # --- _JIECUNIT_EXTERN_PROGRAMS dispatcher ---
    lines.append(f"{{#define {_EXTERN_PROGRAMS_MACRO_NAME}_N(n, ...) "
                 f"{_EXTERN_PROGRAMS_MACRO_NAME}_@@n(__VA_ARGS__)}}")
    lines.append(f"{{#define {_EXTERN_PROGRAMS_MACRO_NAME}(n, ...) "
                 f"{_EXTERN_PROGRAMS_MACRO_NAME}_N(n, __VA_ARGS__)}}")
    lines.append('')

    lines.append(_FOOTER)
    return '\n'.join(lines)


def main():
    # type: () -> None
    parser = argparse.ArgumentParser(description='Generate jiecunit_macros.iec')
    parser.add_argument('--max', type=int, default=512,
                        help='Maximum N for N-arity macros (default: 512)')
    args = parser.parse_args()

    content = generate(args.max)
    out_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        'src', 'jiecunit_macros.iec')
    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(content)
    print('Generated: {}'.format(out_path))
    print('  {}_N, {}_N, and {}_N for N = 1..{}'.format(
        _STRINGIFY_MACRO_NAME, _TASK_BIND_MACRO_NAME, _EXTERN_PROGRAMS_MACRO_NAME, args.max))


if __name__ == '__main__':
    main()
